channels:
- conda-forge
dependencies:
- python=3.11.7
- pip<=24.0
- pip:
  - mlflow==2.15.1
  - cloudpickle==3.0.0
  - packaging==23.2
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
  - typing-extensions==4.9.0
name: mlflow-env
