channels:
- conda-forge
dependencies:
- python=3.11.7
- pip<=24.0
- pip:
  - mlflow==2.15.1
  - cloudpickle==3.0.0
  - numpy==1.24.2
  - psutil==5.9.8
  - scikit-learn==1.2.2
  - scipy==1.11.4
name: mlflow-env
